import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
        <link rel="icon" href="/favicon.ico" sizes="any" />

        {/* <SEO Meta Tags></SEO> */}
        <title>Aria Shabry - Software Engineer Portfolio</title>
        <meta
          name="description"
          content="Professional portfolio of Aria Shabry, a Full Stack Software Engineer specializing in web and mobile development. View my latest projects including UNRI Student Admission, K-Style Hub, and more."
        />
        <meta
          name="keywords"
          content="Aria Shabry, Software Engineer, Web Developer, Mobile Developer, Full Stack Developer, React, Golang, Laravel, Flutter"
        />
        <meta name="author" content="Aria Shabry" />

        {/* <!-- Open Graph Meta Tags for social sharing --> */}
        <meta property="og:title" content="Aria Shabry - Software Engineer Portfolio" />
        <meta
          property="og:description"
          content="Professional portfolio of Aria Shabry, a Full Stack Software Engineer specializing in web and mobile development."
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://ariashabry.github.io/portfolio/" />
        <meta property="og:image" content="/src/assets/og-image.jpg" />

        {/* <!-- Twitter Card Meta Tags --> */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Aria Shabry - Software Engineer Portfolio" />
        <meta
          name="twitter:description"
          content="Professional portfolio of Aria Shabry, a Full Stack Software Engineer specializing in web and mobile development."
        />
        <meta name="twitter:image" content="/src/assets/og-image.jpg" />

        {/* <!-- Canonical URL --> */}
        <link rel="canonical" href="https://ariashabry.github.io/portfolio/" />

        {/* <!-- Existing tags --> */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Big+Shoulders:opsz,wght@10..72,100..900&family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap"
          rel="stylesheet"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              name: "Aria Shabry - Software Engineer Portfolio",
              url: "https://ariashabry.github.io/portfolio/",
              description:
                "Professional portfolio of Aria Shabry, a Full Stack Software Engineer specializing in web and mobile development.",
              author: {
                "@type": "Person",
                name: "Aria Shabry",
              },
            }),
          }}
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
